"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./invoice.controller'), create = _b.create, createFromAppointment = _b.createFromAppointment, index = _b.index, pay = _b.pay, payments = _b.payments;
var router = new Router({ prefix: '/invoices' });
router.post('/', authenticate(), authorize(ACCESS_GROUPS.BILLING_MANAGERS), create);
router.post('/appointments/:appointmentId', authenticate(), authorize(ACCESS_GROUPS.BILLING_MANAGERS), createFromAppointment);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.BILLING_MANAGERS), index);
router.patch('/:id/pay', authenticate(), authorize(ACCESS_GROUPS.BILLING_MANAGERS), pay);
router.get('/:id/payments', authenticate(), authorize(ACCESS_GROUPS.BILLING_MANAGERS), payments);
module.exports = router;
