"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./bed.controller'), create = _b.create, index = _b.index, available = _b.available;
var router = new Router({ prefix: '/beds' });
router.post('/', authenticate(), authorize(ACCESS_GROUPS.OPERATIONS_MANAGERS), create);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), index);
router.get('/available', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), available);
module.exports = router;
