const ROLES = Object.freeze({
  ADMIN: 'admin',
  TENANT: 'tenant',
  DOCTOR: 'doctor',
  STAFF: 'staff',
  PATIENT: 'patient'
});

const ACCESS_GROUPS = Object.freeze({
  PLATFORM_ADMINS: [ROLES.ADMIN],
  TENANT_ADMINS: [ROLES.ADMIN, ROLES.TENANT],
  USER_MANAGERS: [ROLES.ADMIN, ROLES.TENANT, ROLES.STAFF],
  APPOINTMENT_MANAGERS: [ROLES.TENANT, ROLES.STAFF],
  BILLING_MANAGERS: [ROLES.TENANT, ROLES.STAFF],
  CLINICAL_OPERATIONS: [ROLES.ADMIN, ROLES.TENANT, ROLES.DOCTOR, ROLES.STAFF],
  OPERATIONS_MANAGERS: [ROLES.ADMIN, ROLES.TENANT, ROLES.STAFF]
});

module.exports = {
  ROLES,
  ACCESS_GROUPS
};
