"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./staff.controller'), create = _b.create, index = _b.index, show = _b.show, update = _b.update, remove = _b.remove;
var router = new Router({ prefix: '/staff' });
router.post('/', authenticate(), authorize(ACCESS_GROUPS.TENANT_ADMINS), create);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.TENANT_ADMINS), index);
router.get('/:id', authenticate(), authorize(ACCESS_GROUPS.TENANT_ADMINS), show);
router.patch('/:id', authenticate(), authorize(ACCESS_GROUPS.TENANT_ADMINS), update);
router.delete('/:id', authenticate(), authorize(ACCESS_GROUPS.TENANT_ADMINS), remove);
module.exports = router;
