"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./admission.controller'), admitFromOpd = _b.admitFromOpd, admitIpd = _b.admitIpd, index = _b.index, update = _b.update, discharge = _b.discharge;
var router = new Router({ prefix: '/admissions' });
router.post('/from-opd', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), admitFromOpd);
router.post('/ipd', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), admitIpd);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), index);
router.patch('/:id', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), update);
router.patch('/:id/discharge', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), discharge);
module.exports = router;
