"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./tenant.controller'), create = _b.create, index = _b.index, show = _b.show, update = _b.update;
var router = new Router({ prefix: '/tenants' });
router.post('/', authenticate(), authorize(ACCESS_GROUPS.PLATFORM_ADMINS), create);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.PLATFORM_ADMINS), index);
router.get('/:id', authenticate(), authorize(ACCESS_GROUPS.TENANT_ADMINS), show);
router.patch('/:id', authenticate(), authorize(ACCESS_GROUPS.TENANT_ADMINS), update);
module.exports = router;
