"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./appointment.controller'), create = _b.create, index = _b.index, show = _b.show, update = _b.update, remove = _b.remove, checkIn = _b.checkIn;
var router = new Router({ prefix: '/appointments' });
router.post('/', authenticate(), authorize(ACCESS_GROUPS.APPOINTMENT_MANAGERS), create);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.APPOINTMENT_MANAGERS), index);
router.get('/:id', authenticate(), authorize(ACCESS_GROUPS.APPOINTMENT_MANAGERS), show);
router.patch('/:id', authenticate(), authorize(ACCESS_GROUPS.APPOINTMENT_MANAGERS), update);
router.delete('/:id', authenticate(), authorize(ACCESS_GROUPS.APPOINTMENT_MANAGERS), remove);
router.post('/:id/check-in', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), checkIn);
module.exports = router;
