"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./patient.controller'), create = _b.create, index = _b.index, show = _b.show, search = _b.search, update = _b.update, remove = _b.remove;
var router = new Router({ prefix: '/patients' });
router.post('/', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), create);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), index);
router.get('/search', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), search);
router.get('/:id', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), show);
router.patch('/:id', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), update);
router.delete('/:id', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), remove);
module.exports = router;
