"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router = require('koa-router');
var _a = require('../../middlewares/auth.middleware'), authenticate = _a.authenticate, authorize = _a.authorize;
var ACCESS_GROUPS = require('../../constants/roles').ACCESS_GROUPS;
var _b = require('./patient.controller'), create = _b.create, index = _b.index, show = _b.show;
var router = new Router({ prefix: '/patients' });
router.post('/', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), create);
router.get('/', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), index);
router.get('/:id', authenticate(), authorize(ACCESS_GROUPS.CLINICAL_OPERATIONS), show);
module.exports = router;
